In [2]:
import pandas as pd
import numpy as np 
from datetime import datetime, timedelta
import matplotlib.pyplot as plt

In [3]:
# DateTime
my_year = 2021
my_month = 1
my_day = 2
my_hour = 15
my_minute = 25
my_second = 10
my_date1 = datetime(my_year, my_month, my_day, my_hour, my_minute, my_second)
print(my_date1)

2021-01-02 15:25:10


In [4]:
my_date2 = datetime(my_year, my_month, my_day) # 3rd Jan 2021 15:25:10
print(my_date2)

2021-01-02 00:00:00


In [5]:
np.array(['2020-03-15', '2020-03-16'], dtype='datetime64')

array(['2020-03-15', '2020-03-16'], dtype='datetime64[D]')

In [6]:
np.array(['2020-03-15', '2020-03-16'], dtype='datetime64[Y]')

array(['2020', '2020'], dtype='datetime64[Y]')

In [7]:
np.array(['2020-03-15', '2020-03-16'], dtype='datetime64[h]')

array(['2020-03-15T00', '2020-03-16T00'], dtype='datetime64[h]')

In [8]:
np.arange('2021-05-06', '2021-06-03', 7, dtype='datetime64[D]')

array(['2021-05-06', '2021-05-13', '2021-05-20', '2021-05-27'],
      dtype='datetime64[D]')

In [9]:
pd.date_range('2020-01-01', periods=7, freq='W')

DatetimeIndex(['2020-01-05', '2020-01-12', '2020-01-19', '2020-01-26',
               '2020-02-02', '2020-02-09', '2020-02-16'],
              dtype='datetime64[ns]', freq='W-SUN')

In [10]:
pd.date_range('Jan 01, 2020', periods=7, freq='2D')

DatetimeIndex(['2020-01-01', '2020-01-03', '2020-01-05', '2020-01-07',
               '2020-01-09', '2020-01-11', '2020-01-13'],
              dtype='datetime64[ns]', freq='2D')

In [ ]:
pd.to_datetime(['1/2/2005', '1/3/2005'])

DatetimeIndex(['2005-01-02', '2005-01-03'], dtype='datetime64[ns]', freq=None)

In [13]:
pd.to_datetime(['1/2/2005', '1/3/2005'], format='%d/%m/%Y')

DatetimeIndex(['2005-02-01', '2005-03-01'], dtype='datetime64[ns]', freq=None)

In [17]:
data = np.random.randn(3, 3)
print(data)

[[-0.15903171  1.40698138 -2.46480207]
 [-0.02046257  0.05454228 -0.47422372]
 [-0.17247602 -1.71825727  0.79740556]]


In [18]:
idx = pd.date_range('2020-01-01', periods=3, freq='D')
df = pd.DataFrame(data, index=idx, columns=['A', 'B', 'C'])
print(df)

                   A         B         C
2020-01-01 -0.159032  1.406981 -2.464802
2020-01-02 -0.020463  0.054542 -0.474224
2020-01-03 -0.172476 -1.718257  0.797406


In [19]:
df.index.max()

Timestamp('2020-01-03 00:00:00')